language: "zh"

pipeline:
  - name: "MitieNLP"
    model: "data/total_word_feature_extractor_zh.dat"
  - name: "JiebaTokenizer"
  - name: "MitieEntityExtractor"
  - name: "MitieFeaturizer"
  - name: "MitieIntentClassifier"
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: RulePolicy
